modelID:
  JCNT: "-poisson -catfix uniform -dgam 1"
  GTRNT: "-gtr -ncat 1 -dgam 1"
  GTR4GNT: "-gtr -ncat 1 -dgam 4"
  MG-F1x4: "-mutsel -catfix uniform -uni"
  MG-F1x4W: "-mutsel -catfix uniform -freeomega -uni"
  MUTSELAAW: "-mutselaa -sbdp -freeomega -uni"
  MUTSELAAwoW: "-mutselaa -sbdp -uni"
simulation:
  geneID: ["WDR91","GPAM","STRIP1","CSRP2BP","HSPA4","MEP1A","MYB","PDE6A","SEMA3D","TNFAIP3"]
empirical:
  geneID: ["EDEM2","COG2","STRIP1","KDM7A","DIS3","MPP5","TNKS","CASR","LRRTM3","ATP8B1","USP6NL","THBS1","WDR3","TGFBI","CDH20","ITGA4","SLC13A1","NRP1","CDCP1","MCCC1","TRIM36","ROR1","RECK","ARID4A","SEMA3D","FAM160B1","NOSTRIN","ARNT","GPD2","VPS45","FNDC3A","PPARGC1A","NRAP","GRHL2","SGPL1","AGBL5","WDR91","TNFAIP3","RPE65","MEP1A","SART3","ACSL3","TLR3","CROT","AMPD1","KDR","P4HA2","ANKRD28","SEMA6D","BRPF1","TMEM57","PAK7","STRIP2","PDE6A","UTP15","KIAA0100","KIAA0368","EXOC1","DYNC1I2","EMC1","DSE","RNF20","MGAT4A","CSRP2BP","TTC17","ANKRD6","MKKS","NHS","FILIP1","ACO1","TBCCD1","MYB","HSPA4","NR2C1","GPR155","MTMR2","CCDC186","COL9A1","LRRC7","DPP8","FN1","TMC1","DAAM1","NNT","VWA9","SLC18A1","SLC17A6","YTHDF2","TYRP1","BOC","PRMT9","RINT1","POMT2","PLEKHA8","TMF1","EIF2AK3","CP","LCP1","ATG13","ANGEL2","ENOX1","BMPR2","WDR36","JAKMIP2","DNTT","POSTN","STON2","ITGA8","EXOSC10","PIK3C3","ETV5","RFX7","RAB3GAP1","SLC38A9","TNIK","EIF2B5","BACE1","PRLR","KIAA1033","PYGL","EFHC1","HHIP","GPAM","ZBTB24","NOD1","ARHGAP12","RAPGEF4","COL8A1","CTTNBP2NL","OGFOD1","NR4A2","SLC4A10","HIVEP2","ADNP","GABRA4","FLT3","GFM2"]
